version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
      MYSQL_DATABASE: ${{ secrets.DB_NAME }}
      MYSQL_USER: ${{ secrets.DB_USERNAME }}
      MYSQL_PASSWORD: ${{ secrets.DB_PASSWORD }}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    image: ${{ secrets.DOCKERHUB_USERNAME }}/github-actions-demo:latest
    container_name: spring_boot_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/${{ secrets.DB_NAME }}
      SPRING_DATASOURCE_USERNAME: ${{ secrets.DB_USERNAME }}
      SPRING_DATASOURCE_PASSWORD: ${{ secrets.DB_PASSWORD }}
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  mysql_data:
