version: '3.8'

services:

  mysql:
    container_name: mysql
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: siv
    restart: always
    networks:
      - testnet

  backend:
    container_name: backend
    image: astar5327/github-actions-demo
    expose:
      - 8080
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - mysql
    networks:
      - testnet


networks:
  mynet:
    driver: bridge