version: '3.8'

services:
  mysql:
    container_name: mysql
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: siv
    restart: always
    networks:
      - mynet
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  backend:
    container_name: backend
    image: astar5327/github-actions-demo
    expose:
      - 8080
    ports:
      - 8080:8080
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - mynet
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/siv
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_PROFILES_ACTIVE: prod

networks:
  mynet:
    driver: bridge
